name : Hello world workflow
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -name: hello_world
      run: echo  "hello world"
      shell : bash
  goodbye:
    steps:
      -name : goodbye_world
      run: echo "goodbye world"
      shell : bash
